const colorThemesStyles = {
  'default': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#4b5563]',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-[#4772fa]',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#e0e0e0] to-[#f5f5f5]',
    asideMenu: 'bg-white',
    substrateBackground: 'bg-[#1919190d]',
    substrateBackgroundAccent: 'bg-[#9ca3af1a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#9ca3af]',
    accentBorder: 'border-[#9ca3af]',
  },
  'sky': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#2563eb]',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#bfdbfe] to-[#e0f2fe]',
    asideMenu: 'bg-linear-[180deg,#60a5fa,#3b82f6,#93c5fd,#93c5fd]',
    substrateBackground: 'bg-[#1919190d]',
    substrateBackgroundAccent: 'bg-[#2563eb1a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#93c5fd]',
    accentBorder: 'border-[#93c5fd]',
  },
  'turquoise': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#0891b2]',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#a5f3fc] to-[#cffafe]',
    asideMenu: 'bg-linear-[180deg,#22d3ee,#06b6d4,#67e8f9,#67e8f9]',
    substrateBackground: 'bg-[#1919190d]',
    substrateBackgroundAccent: 'bg-[#0891b21a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#67e8f9]',
    accentBorder: 'border-[#67e8f9]',
  },
  'teal': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#0f766e]',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#99f6e4] to-[#ccfbf1]',
    asideMenu: 'bg-linear-[180deg,#2dd4bf,#14b8a6,#5eead4,#5eead4]',
    substrateBackground: 'bg-[#1919190d]',
    substrateBackgroundAccent: 'bg-[#0f766e1a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#5eead4]',
    accentBorder: 'border-[#5eead4]',
  },
  'green': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#15803d]',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#bbf7d0] to-[#dcfce7]',
    asideMenu: 'bg-linear-[180deg,#4ade80,#22c55e,#86efac,#86efac]',
    substrateBackground: 'bg-[#1919190d]',
    substrateBackgroundAccent: 'bg-[#15803d1a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#86efac]',
    accentBorder: 'border-[#86efac]',
  },
  'apricot': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#ea580c]',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#fed7aa] to-[#ffedd5]',
    asideMenu: 'bg-linear-[180deg,#fb923c,#f97316,#fdba74,#fdba74]',
    substrateBackground: 'bg-[#1919190d]',
    substrateBackgroundAccent: 'bg-[#ea580c1a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#fdba74]',
    accentBorder: 'border-[#fdba74]',
  },
  'peach': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#db2777]',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#fbd9d7] to-[#fef2f2]',
    asideMenu: 'bg-linear-[180deg,#f9a8a4,#f472b6,#fecaca,#fecaca]',
    substrateBackground: 'bg-[#1919190d]',
    substrateBackgroundAccent: 'bg-[#db27771a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#fecaca]',
    accentBorder: 'border-[#fecaca]',
  },
  'lilac': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#8672d3]',
    asideMenuIcons: 'fill-white opacity-50',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#e0e2f8] to-[#f4ecf9]',
    asideMenu: 'bg-linear-[180deg,#9aa1d9,#9aa1d9,#d7bedc,#d7bedc]',
    substrateBackground: 'bg-[#1919190d]',
    substrateBackgroundAccent: 'bg-[#8672d31a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#8672d3]',
    accentBorder: 'border-[#8672d3]',
  },
  'ebony': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#d1d5db]',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#4b5563] to-[#6b7280]',
    asideMenu: 'bg-linear-[180deg,#1f2937,#374151,#4b5563,#4b5563]',
    substrateBackground: 'bg-[#19191966]',
    substrateBackgroundAccent: 'bg-[#d1d5db1a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#4b5563]',
    accentBorder: 'border-[#4b5563]',
  },
  'blue': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#1e40af]',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#bfdbfe] to-[#dbeafe]',
    asideMenu: 'bg-linear-[180deg,#3b82f6,#1d4ed8,#93c5fd,#93c5fd]',
    substrateBackground: 'bg-[#1919190d]',
    substrateBackgroundAccent: 'bg-[#1e40af1a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#93c5fd]',
    accentBorder: 'border-[#93c5fd]',
  },
  'gray': {
    textColor: 'text-[#191919d9]',
    textMuted: 'text-[#19191966]',
    textAccent: 'text-[#374151]',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-icons',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#d1d5db] to-[#e5e7eb]',
    asideMenu: 'bg-linear-[180deg,#6b7280,#4b5563,#9ca3af,#9ca3af]',
    substrateBackground: 'bg-[#1919190d]',
    substrateBackgroundAccent: 'bg-[#3741511a]',
    siteBackground: 'bg-white',
    accentBackground: 'bg-[#9ca3af]',
    accentBorder: 'border-[#9ca3af]',
  },
  'dark': {
    textColor: 'text-white',
    textMuted: 'text-[#d1d5db66]',
    textAccent: 'text-white',
    asideMenuIcons: 'fill-icons',
    asideMenuIconsAccent: 'fill-white',
    icons: 'fill-white opacity-70',
    iconsAccent: '',
    projectsList: 'bg-gradient-to-b from-[#374151] to-[#4b5563]',
    asideMenu: 'bg-linear-[180deg,#1f2937,#111827,#374151,#374151]',
    substrateBackground: 'bg-[#19191966]',
    substrateBackgroundAccent: 'bg-[#3741511a]',
    siteBackground: 'bg-[#111827]',
    accentBackground: 'bg-[#374151]',
    accentBorder: 'border-[#374151]',
  },
};
export default colorThemesStyles;
